Areas/Cms/Controllers/NhanVienController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using baitapcuoimonweb.Models;

namespace baitapcuoimonweb.Areas.Cms.Controllers
{
    
    public class NhanVienController : Controller
    {
        private ShopDienThoaiEntities db = new ShopDienThoaiEntities();

        // GET: Cms/NhanVien

        [HttpGet]
        public ActionResult Index(string search, string Gender,string quequan, string Chucvu)
        {
            List<Tb_NhanVien> list;
            if (search == null || search == "")
            {
                if (Gender == null || Gender == "")
                {
                   
                     if (quequan == null || quequan == "")
                     {
                        if (Chucvu == null || Chucvu == "")
                        {
                            list = db.Tb_NhanVien.ToList();
                        }
                        else
                        {
                            list = db.Tb_NhanVien.Where(x => x.ChucVu == Chucvu).ToList();
                        }
                    }
                     else {
                        if (Chucvu == null || Chucvu == "")
                        {
                            list = db.Tb_NhanVien.Where(x => x.QueQuan == quequan).ToList();
                        }
                        else
                        {
                            list = db.Tb_NhanVien.Where(x => x.ChucVu == Chucvu && x.QueQuan == quequan).ToList();
                        }
                        
                     }
                }
                else
                {

                    if (quequan == null || quequan == "")
                    {
                        if (Chucvu == null || Chucvu == "")
                        {
                            list = db.Tb_NhanVien.Where(x => x.GioiTinh == Gender).ToList();
                        }
                        else
                        {
                            list = db.Tb_NhanVien.Where(x => x.ChucVu == Chucvu && x.GioiTinh == Gender).ToList();
                        }
                    }
                    else
                    {
                        if (Chucvu == null || Chucvu == "")
                        {
                            list = db.Tb_NhanVien.Where(x => x.GioiTinh == Gender && x.QueQuan==quequan).ToList();
                        }
                        else
                        {
                            list = db.Tb_NhanVien.Where(x => x.ChucVu == Chucvu && x.GioiTinh == Gender &&x.QueQuan==quequan).ToList();
                        }
                      
                    }
                   
                }
            }
            else
            {
                if (Gender == null || Gender == "")
                {

                    if (quequan == null || quequan == "")
                    {
                        if (Chucvu == null || Chucvu == "")
                        {
                            list = db.Tb_NhanVien.Where(x => x.TenNV == search).ToList();
                        }
                        else
                        {
                            list = db.Tb_NhanVien.Where(x => x.ChucVu == Chucvu&& x.TenNV == search).ToList();
                        }
                    }
                    else
                    {
                        if (Chucvu == null || Chucvu == "")
                        {
                            list = db.Tb_NhanVien.Where(x => x.QueQuan == quequan&&x.TenNV == search).ToList();
                        }
                        else
                        {
                            list = db.Tb_NhanVien.Where(x => x.ChucVu == Chucvu && x.QueQuan == quequan&& x.TenNV == search).ToList();
                        }

                    }
                }
                else
                {

                    if (quequan == null || quequan == "")
                    {
                        if (Chucvu == null || Chucvu == "")
                        {
                            list = db.Tb_NhanVien.Where(x => x.GioiTinh == Gender&& x.TenNV == search).ToList();
                        }
                        else
                        {
                            list = db.Tb_NhanVien.Where(x => x.TenNV == search&& x.ChucVu == Chucvu && x.GioiTinh == Gender).ToList();
                        }
                    }
                    else
                    {
                        if (Chucvu == null || Chucvu == "")
                        {
                            list = db.Tb_NhanVien.Where(x => x.TenNV == search&& x.GioiTinh == Gender && x.QueQuan == quequan).ToList();
                        }
                        else
                        {
                            list = db.Tb_NhanVien.Where(x => x.TenNV == search&& x.ChucVu == Chucvu && x.GioiTinh == Gender && x.QueQuan == quequan).ToList();
                        }

                    }

                }
            }
            ViewBag.Chucvu = new SelectList(db.Tb_NhanVien, "ChucVu", "ChucVu");

            return View(list);
        }

        // GET: Cms/NhanVien/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_NhanVien tb_NhanVien = db.Tb_NhanVien.Find(id);
            if (tb_NhanVien == null)
            {
                return HttpNotFound();
            }
            return View(tb_NhanVien);
        }

        // GET: Cms/NhanVien/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cms/NhanVien/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TenNV,SDT,CMND,QueQuan,ChucVu,TenDanhNhap,MatKhau,NgaySinh,GioiTinh")] Tb_NhanVien tb_NhanVien)
        {
            if (ModelState.IsValid)
            {
                db.Tb_NhanVien.Add(tb_NhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tb_NhanVien);
        }

        // GET: Cms/NhanVien/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_NhanVien tb_NhanVien = db.Tb_NhanVien.Find(id);
            if (tb_NhanVien == null)
            {
                return HttpNotFound();
            }
            return View(tb_NhanVien);
        }

        // POST: Cms/NhanVien/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TenNV,SDT,CMND,QueQuan,ChucVu,TenDanhNhap,MatKhau,NgaySinh,GioiTinh")] Tb_NhanVien tb_NhanVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_NhanVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tb_NhanVien);
        }

        // GET: Cms/NhanVien/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_NhanVien tb_NhanVien = db.Tb_NhanVien.Find(id);
            if (tb_NhanVien == null)
            {
                return HttpNotFound();
            }
            List<Tb_PhieuNhap> phieunhap = db.Tb_PhieuNhap.Where(x => x.IdNhanVien == id).ToList();
            if ( phieunhap.Count != 0)
            {
                ViewBag.loixoa = 1;
            }
            return View(tb_NhanVien);
        }

        // POST: Cms/NhanVien/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Tb_NhanVien tb_NhanVien = db.Tb_NhanVien.Find(id);
            db.Tb_NhanVien.Remove(tb_NhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Cms/Views/NhanVien/Create.cshtml
@model baitapcuoimonweb.Models.Tb_NhanVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tb_NhanVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QueQuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QueQuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChucVu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChucVu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChucVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDanhNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDanhNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDanhNhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Cms/Views/NhanVien/Delete.cshtml
@model baitapcuoimonweb.Models.Tb_NhanVien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tb_NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QueQuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QueQuan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChucVu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChucVu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenDanhNhap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDanhNhap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">

            @if (ViewBag.loixoa == 1)
            {
                <p>bạn không thể xóa do sản phẩm đang được bán</p>
            }
            else
            {
                <input type="submit" value="Delete" class="btn btn-default" />
            }
            |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Cms/Views/NhanVien/Details.cshtml
@model baitapcuoimonweb.Models.Tb_NhanVien

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Tb_NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QueQuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QueQuan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChucVu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChucVu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenDanhNhap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDanhNhap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Cms/Views/NhanVien/Edit.cshtml
@model baitapcuoimonweb.Models.Tb_NhanVien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tb_NhanVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TenNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QueQuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QueQuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChucVu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChucVu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChucVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDanhNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDanhNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDanhNhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Cms/Views/NhanVien/Index.cshtml
@model IEnumerable<baitapcuoimonweb.Models.Tb_NhanVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}

<h2>Quản Lý nhân viên</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "NhanVien", FormMethod.Get))
{
    <p>lọc nhân viên</p>
    <div style="display:flex ; margin-bottom:20px">
        <div style="margin-right:10px">
            <label style="margin-right:10px">Tên: </label>
            @Html.TextBox("search")

        </div>

        <div style="margin-right:10px">
            <label style="margin-right:10px">Giới Tính</label>
            <input id="Gender" name="Gender" value="Nam" type="radio">
            <span style="margin-right:10px">Nam</span>

            <input id="Gender" name="Gender" value="Nữ" type="radio">
            <span style="margin-right:10px"> Nữ</span>
        </div>
        <div style="margin-right:10px">
            <label style="margin-right:10px">Quê Quán: </label>
            @Html.TextBox("quequan")

        </div>
        <div style="margin-right:10px">
            <label style="margin-right:10px">Chức vụ: </label>
            @Html.DropDownList("Chucvu", "--tất cả danh mục--")

        </div>
        <div style="margin-right:10px">
            <label style="margin-right:10px">Số Điện Thoại: </label>
            @Html.TextBox("Số Điện Thoại")

        </div>

    </div>

    <input type="submit" value="lọc" style="border:#333 solid 2px; width:70px;" />


}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenNV)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CMND)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QueQuan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChucVu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenDanhNhap)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MatKhau)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenNV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CMND)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QueQuan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChucVu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenDanhNhap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatKhau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>