Areas/Cms/Controllers/SanPhamcmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using baitapcuoimonweb.Models;

namespace baitapcuoimonweb.Areas.Cms.Controllers
{
   [Authorize]
    public class SanPhamcmsController : Controller
    {
       
        private ShopDienThoaiEntities db = new ShopDienThoaiEntities();

        // GET: Cms/SanPham
        public ActionResult Index(string search,string gia,string IdDanhMuc,string KhuyenMai)
        {
          
            ViewBag.IdDanhMuc = new SelectList(new List<string>() { "điện thoại", "phụ kiện" });

            ViewBag.HangSanXuat = new SelectList(db.Tb_DanhMucSanPham, "HangSanXuat", "HangSanXuat");
            
            ViewBag.KhuyenMai = new SelectList(db.Tb_SanPham, "Id", "KhuyenMai");
            List<Tb_SanPham> tb_SanPham=new List<Tb_SanPham>();
            
            if(search==null||search==""){
                if(IdDanhMuc==null||IdDanhMuc=="" ){
                    if(KhuyenMai==null||KhuyenMai==""){
                        if (gia == null || gia == "")
                        {
                            tb_SanPham = db.Tb_SanPham.Include(t => t.Tb_DanhMucSanPham).ToList();
                        }
                        else
                        {
                            if (gia == "1")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan <= 5000000).Include(t => t.Tb_DanhMucSanPham).ToList();
                            } else if (gia == "2")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 5000000 && t.GiaBan <= 10000000).Include(t => t.Tb_DanhMucSanPham).ToList();
                            } else if (gia == "3") {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 10000000 && t.GiaBan <= 15000000).Include(t => t.Tb_DanhMucSanPham).ToList();

                            } else
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 15000000 ).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                        }
                    }
                    else
                    {
                        if (gia == null || gia == "")
                        {
                            tb_SanPham = db.Tb_SanPham.Where(t => t.KhuyenMai==int.Parse(KhuyenMai)).Include(t => t.Tb_DanhMucSanPham).ToList();
                        }
                        else
                        {
                            if (gia == "1")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan <= 5000000&& t.KhuyenMai == int.Parse(KhuyenMai)).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                            else if (gia == "2")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 5000000 && t.GiaBan <= 10000000&& t.KhuyenMai == int.Parse(KhuyenMai)).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                            else if (gia == "3")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 10000000 && t.GiaBan <= 15000000&& t.KhuyenMai == int.Parse(KhuyenMai)).Include(t => t.Tb_DanhMucSanPham).ToList();

                            }
                            else
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 15000000&& t.KhuyenMai == int.Parse(KhuyenMai)).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                        }
                    }
                }
                else
                {
                    if (KhuyenMai == null || KhuyenMai == "")
                    {
                        if (gia == null || gia == "")
                        {
                            tb_SanPham = db.Tb_SanPham.Where(t => t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();
                        }
                        else
                        {
                            if (gia == "1")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan <= 5000000&& t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                            else if (gia == "2")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 5000000 && t.GiaBan <=10000000 && t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                            else if (gia == "3")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 10000000 && t.GiaBan <= 15000000 && t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();

                            }
                            else
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 15000000 && t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                        }
                    }
                    else
                    {
                        if (gia == null || gia == "")
                        {
                            tb_SanPham = db.Tb_SanPham.Where(t => t.KhuyenMai == int.Parse(KhuyenMai) && t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();
                        }
                        else
                        {
                            if (gia == "1")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan <= 5000000 && t.KhuyenMai == int.Parse(KhuyenMai) && t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                            else if (gia == "2")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 5000000 && t.GiaBan <= 10000000 && t.KhuyenMai == int.Parse(KhuyenMai) && t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                            else if (gia == "3")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 10000000 && t.GiaBan <= 15000000 && t.KhuyenMai == int.Parse(KhuyenMai) && t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();

                            }
                            else
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 15000000 && t.KhuyenMai == int.Parse(KhuyenMai) && t.Tb_DanhMucSanPham.LoaiSanPham==IdDanhMuc).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                        }
                    }
                }
            }
            else
            {
                if (IdDanhMuc == null || IdDanhMuc == "")
                {
                    if (KhuyenMai == null || KhuyenMai == "")
                    {
                        if (gia == null || gia == "")
                        {
                            tb_SanPham = db.Tb_SanPham.Where(t => t.TenSanPham==search).Include(t => t.Tb_DanhMucSanPham).ToList();
                        }
                        else
                        {
                            if (gia == "1")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan <= 5000000&& t.TenSanPham == search).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                            else if (gia == "2")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 5000000 && t.GiaBan <= 10000000 && t.TenSanPham == search).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                            else if (gia == "3")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 10000000 && t.GiaBan <= 15000000 && t.TenSanPham == search).Include(t => t.Tb_DanhMucSanPham).ToList();

                            }
                            else
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 15000000 && t.TenSanPham == search).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                        }
                    }
                    else
                    {
                        if (gia == null || gia == "")
                        {
                            tb_SanPham = db.Tb_SanPham.Where(t => t.KhuyenMai == int.Parse(KhuyenMai) && t.TenSanPham == search).Include(t => t.Tb_DanhMucSanPham).ToList();
                        }
                        else
                        {
                            if (gia == "1")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan <= 5000000 && t.KhuyenMai == int.Parse(KhuyenMai) && t.TenSanPham == search).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }
                            else if (gia == "2")
                            {
                                tb_SanPham = db.Tb_SanPham.Where(t => t.GiaBan > 5000000 && t.GiaBan <= 10000000 && t.KhuyenMai == int.Parse(KhuyenMai) && t.TenSanPham == search).Include(t => t.Tb_DanhMucSanPham).ToList();
                            }

Areas/Cms/Views/SanPhamcms/Create.cshtml
@model baitapcuoimonweb.Models.Tb_SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "SanPhamcms", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Tb_SanPham</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <b class="control-label col-md-2"> Loại sản phẩm</b>
        <div class="col-md-10">
            @Html.DropDownList("Loaisanpham", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdDanhMuc, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <b class = "control-label col-md-2" > Hãng sản xuất</b>
       
        <div class="col-md-10">
            @Html.DropDownList("HangSanXuat", null, htmlAttributes: new { @class = "form-control" })
          
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaGoc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaGoc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaGoc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KhuyenMai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KhuyenMai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KhuyenMai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AnhSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Image" />

            @Html.ValidationMessageFor(model => model.AnhSanPham, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Cms/Views/SanPhamcms/Delete.cshtml
@model baitapcuoimonweb.Models.Tb_SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tb_SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhuyenMai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhuyenMai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhSanPham)
        </dt>

        <dd>
            <img src="@Model.AnhSanPham" width="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tb_DanhMucSanPham.LoaiSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tb_DanhMucSanPham.LoaiSanPham)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        
        @if (ViewBag.loixoa == 1)
        {
            <p>bạn không thể xóa do sản phẩm đang được bán</p>
        }
        else
        {
            <input type="submit" value="Delete" class="btn btn-default" />
        }
        |
        @Html.ActionLink("Back to List", "Index")
    </div>
    }
</div>

Areas/Cms/Views/SanPhamcms/Details.cshtml
@model baitapcuoimonweb.Models.Tb_SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Tb_SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhuyenMai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhuyenMai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhSanPham)
        </dt>

        <dd>

            <img src="@Model.AnhSanPham" width="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tb_DanhMucSanPham.LoaiSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tb_DanhMucSanPham.LoaiSanPham)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Cms/Views/SanPhamcms/Edit.cshtml
@model baitapcuoimonweb.Models.Tb_SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "SanPhamcms", FormMethod.Post, new { enctype = "multipart / form - data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Tb_SanPham</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <b class="control-label col-md-2"> loại sản phẩm</b>
        <div class="col-md-10">
            @Html.DropDownList("Loaisanpham", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdDanhMuc, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <b class="control-label col-md-2"> hãng sản xuất</b>

        <div class="col-md-10">
            @Html.DropDownList("HangSanXuat", null, htmlAttributes: new { @class = "form-control" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaGoc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaGoc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaGoc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KhuyenMai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KhuyenMai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KhuyenMai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AnhSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AnhSanPham, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AnhSanPham, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Cms/Views/SanPhamcms/Index.cshtml
@model IEnumerable<baitapcuoimonweb.Models.Tb_SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Cms/Views/Shared/_CMSpage.cshtml";
}



<h2>Sản Phẩm</h2>




<p style="border:#333 solid 2px; width:70px; ">
    <b>@Html.ActionLink("Thêm Mới", "Create")</b>
</p>
@using (Html.BeginForm("Index", "SanPhamcms", FormMethod.Get))
{
    <p>lọc nhân viên</p>
    <div style="display:flex ; margin-bottom:20px">
        <div style="margin-right:10px">
            <label style="margin-right:10px">Tên: </label>
            @Html.TextBox("search")

        </div>

        <div style="margin-right:10px">
            <label style="margin-right:10px">Giá</label>
            <input id="gia" name="gia" value="1" type="radio">
            <span style="margin-right:10px"> dưới 5,000,000</span>

            <input id="gia" name="gia" value="2" type="radio">
            <span style="margin-right:10px"> 5,000,000-10,000,000</span>
            <input id="gia" name="gia" value="3" type="radio">
            <span style="margin-right:10px"> 10,000,000-15,000,000</span>
            <input id="gia" name="gia" value="4" type="radio">
            <span style="margin-right:10px"> >15,000,000</span>
        </div>
        <div style="margin-right:10px; display:flex;">
            <label style="margin-right:10px; ">Loại sản phẩm: </label>
            @Html.DropDownList("IdDanhMuc", "--chọn danh muc--")

        </div>
       

    </div>

    <input type="submit" value="lọc" style="border:#333 solid 2px; width:70px;" />


}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GiaGoc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KhuyenMai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GhiChu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnhSanPham)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tb_DanhMucSanPham.LoaiSanPham)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tb_DanhMucSanPham.HangSanXuat)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenSanPham)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaGoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhuyenMai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GhiChu)
            </td>
            <td>
                <img src="@item.AnhSanPham" width="100" />

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tb_DanhMucSanPham.LoaiSanPham)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tb_DanhMucSanPham.HangSanXuat)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>